# Generated by Django 3.2.17 on 2023-06-02 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('claim', '0013_feedbackprompt'),
        ('claim', '0014_auto_20220829_2102'),
    ]

    operations = [
    ]
