# Generated by Django 3.2.17 on 2023-02-13 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('claim', '0014_auto_20220829_2102'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='claim',
            options={'managed': True},
        ),
    ]
