# Generated by Django 3.2.17 on 2023-02-13 09:18

import core.fields
import datetime
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0001_initial'),
        ('insuree', '0013_auto_20211103_1023'),
        ('core', '0016_add_last_login_on_interactive_user'),
        ('location', '0008_add_enrollment_officer_gql_query_location_right'),
        ('medical', '0003_mutations'),
        ('claim', '0015_prohibit_interaction_for_enrolment_officer'),
    ]

    operations = [
        migrations.AddField(
            model_name='claim',
            name='program',
            field=models.ForeignKey(db_column='program', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='claim_program', to='program.program'),
        )
    ]
