# Generated by Django 3.2.18 on 2023-03-02 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('claim', '0016_auto_20230213_0918'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='claim',
            options={'managed': False},
        ),
    ]
