# Generated by Django 3.2.18 on 2023-05-04 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('claim', '0013_feedbackprompt'),
        ('claim', '0016_auto_20230213_0918'),
    ]

    operations = [
    ]
