# Generated by Django 3.2.18 on 2023-03-15 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('claim', '0013_feedbackprompt'),
        ('claim', '0017_alter_claim_options'),
    ]

    operations = [
    ]
