# Generated by Django 3.2.22 on 2023-10-08 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claim', '0018_auto_20230926_1712'),
    ]

    operations = [
        migrations.AddField(
            model_name='claim',
            name='prescriber_type',
            field=models.SmallIntegerField(blank=True, db_column='PrescriberType', null=True),
        ),
    ]
