# Generated by Django 3.2.21 on 2023-09-18 21:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('claim', '0018_alter_jsonext_column'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='claim',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='feedback',
            options={'managed': True},
        ),
    ]
