# Generated by Django 3.2.21 on 2023-09-18 21:58

import core.fields
import datetime
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('claim', '0018_auto_20230918_2140'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='age',
            field=models.SmallIntegerField(blank=True, db_column='Age', null=True),
        ),
        # migrations.AddField(
        #     model_name='feedback',
        #     name='claim',
        #     field=models.OneToOneField(blank=True, db_column='ClaimID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='claim.claim'),
        # ),
        migrations.AddField(
            model_name='feedback',
            name='means_information',
            field=models.CharField(blank=True, db_column='MeansInformation', max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='feedback',
            name='policy_national',
            field=models.BooleanField(blank=True, db_column='PolicyNational', null=True),
        ),
        migrations.AddField(
            model_name='feedback',
            name='pregnant',
            field=models.BooleanField(blank=True, db_column='Pregnant', null=True),
        ),
        migrations.AddField(
            model_name='feedback',
            name='sexe',
            field=models.CharField(blank=True, db_column='Sexe', max_length=15, null=True),
        ),
        # migrations.AddField(
        #     model_name='feedback',
        #     name='uuid',
        #     field=models.CharField(db_column='FeedbackUUID', default=uuid.uuid4, max_length=36, unique=True),
        # ),
        migrations.AlterField(
            model_name='feedback',
            name='asessment',
            field=models.IntegerField(blank=True, db_column='Asessment', null=True),
        ),
        # migrations.AlterField(
        #     model_name='feedback',
        #     name='validity_from',
        #     field=core.fields.DateTimeField(db_column='ValidityFrom', default=datetime.datetime.now),
        # ),
    ]
