# Generated by Django 3.2.23 on 2023-11-02 11:55

import core.fields
import datetime
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('claim', '0019_auto_20230918_2158'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='claim',
            options={'managed': True},
        ),
    ]
