# Generated by Django 3.2.23 on 2023-11-02 11:55

import core.fields
import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('claim', '0020_auto_20231102_1155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claim',
            name='code',
            field=models.CharField(db_column='ClaimCode', max_length=20),
        ),
    ]
