# Generated by Django 3.2.23 on 2023-11-09 15:21

import core.fields
import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('claim', '0021_auto_20231102_1155'),
    ]

    operations = [
        migrations.AddField(
            model_name='claimserviceitem',
            name='qty_adjusted',
            field=models.IntegerField(blank=True, db_column='qty_adjusted', null=True),
        ),
        migrations.AddField(
            model_name='claimserviceservice',
            name='qty_adjusted',
            field=models.IntegerField(blank=True, db_column='qty_adjusted', null=True),
        ),
    ]
