# Generated by Django 3.2.23 on 2024-01-30 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claim', '0022_auto_20240130_1153'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='claim',
            index=models.Index(fields=['code', 'status'], name='IX_tblClaim_code_insuree_uuid_status'),
        )
    ]
