# Generated by Django 4.2.20 on 2025-03-11 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('claim', '0015_prohibit_interaction_for_enrolment_officer'),
        ('claim', '0018_alter_jsonext_column'),
        ('claim', '0019_auto_20230615_1055'),
        ('claim', '0021_auto_20230818_0914'),
        ('claim', '0022_add_index_tblClaim_240622'),
        ('claim', '0022_alter_feedbackprompt_phone_number'),
        ('claim', '0022_auto_20240130_1153'),
        ('claim', '0025_auto_20231205_1455'),
        ('claim', '0025_auto_20240130_1153'),
        ('claim', '0026_add_sequences'),
        ('claim', '0031_merge_20240318_1324'),
        ('claim', '0033_delete_RoleRight'),
    ]

    operations = [
    ]
