# Generated by Django 4.2.25 on 2026-01-09 11:14


from django.db import migrations, models



class Migration(migrations.Migration):

    dependencies = [
        ('claim', '0034_merge_20250311_1027'),
    ]

    operations = [
        migrations.AddField(
            model_name='claim',
            name='pregnancy_age',
            field=models.PositiveSmallIntegerField(blank=True, db_column='PregnancyAge', null=True),
        ),
    ]
