# Generated by Django 4.2.25 on 2026-01-19 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claim', '0035_add_field_pregnancy_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='claim',
            name='source',
            field=models.CharField(blank=True, choices=[('WEB', 'Web'), ('MOB', 'Mobile'), ('XML', 'Import XML')], default=None, max_length=10, null=True),
        ),
    ]
