# Generated by Django 4.2.29 on 2026-08-20 13:12
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claim', '0036_add_field_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='claim',
            name='amount_audited',
            field=models.DecimalField(blank=True, db_column='amountAudited', decimal_places=2, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='claim',
            name='audit_explanation',
            field=models.CharField(blank=True, db_column='AuditExplanation', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='claim',
            name='audited',
            field=models.BooleanField(blank=True, db_column='Audited', null=True),
        ),
        migrations.AddField(
            model_name='claim',
            name='claim_category',
            field=models.CharField(blank=True, db_column='ClaimCategoryAudit', max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='claim',
            name='from_rejected_to_valuated',
            field=models.BooleanField(blank=True, db_column='RejectedToValuated', null=True),
        ),
        migrations.AddField(
            model_name='claimserviceitem',
            name='qty_audited',
            field=models.DecimalField(blank=True, db_column='qtyAudided', decimal_places=2, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='claimserviceservice',
            name='qty_audited',
            field=models.DecimalField(blank=True, db_column='qtyAudided', decimal_places=2, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='claim',
            name='audit_status',
            field=models.CharField(blank=True, db_column='auditStatus', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='claim',
            name='rejection_motive',
            field=models.CharField(blank=True, db_column='rejectionMotive', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='claim',
            name='rejection_reason_after_audit',
            field=models.CharField(blank=True, db_column='rejectionReasonAfterAudit', max_length=500, null=True),
        )
    ]
