# Generated by Django 4.2.29 on 2026-05-26 00:26
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claim', '0036_add_field_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='claim',
            name='last_updater_ip_address',
            field=models.CharField(blank=True, db_column='LastUpdaterIpAddress', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='claim',
            name='user_entered_ip_address',
            field=models.CharField(blank=True, db_column='UserEnteredIpAddress', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='claim',
            name='user_processed_ip_address',
            field=models.CharField(blank=True, db_column='UserProcessedIpAddress', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='claim',
            name='user_reviewed_ip_address',
            field=models.CharField(blank=True, db_column='UserReviewedIpAddress', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='claim',
            name='user_submit_ip_address',
            field=models.CharField(blank=True, db_column='UserSubmitIpAddress', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='claim',
            name='user_valuated_ip_address',
            field=models.CharField(blank=True, db_column='UserValuatedIpAddress', max_length=50, null=True),
        )
    ]
