# Generated by Django 4.2.11 on 2025-10-31 11:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('claim', '0036_claim_care_type_claim_refer_from_claim_refer_to_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='claim',
            name='is_pre_authorization',
            field=models.BooleanField(blank=True, default=False, null=True),
        )
    ]
