# Generated by Django 4.2.11 on 2025-11-02 09:34

import core.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('claim', '0037_is_pre_authorization_and_more'),
    ]

    operations = [
        
        migrations.AddField(
            model_name='claim',
            name='code_pre_authorization',
            field=models.CharField(blank=True, db_column='ClaimPreAuthorizationCode', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='claim',
            name='date_pre_authorization',
            field=core.fields.DateTimeField(blank=True, db_column='DatePreAuthorization', null=True),
        ),
        migrations.AlterField(
            model_name='claim',
            name='code',
            field=models.CharField(blank=True, db_column='ClaimCode', max_length=50, null=True),
        ),
    ]
