# Generated by Django 4.2.29 on 2026-08-26 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claim', '0037_claim_amount_audited_claim_audit_explanation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claim',
            name='rejection_motive',
            field=models.SmallIntegerField(blank=True, db_column='rejectionMotive', max_length=2, null=True),
        )
    ]
