# Generated by Django 4.2.11 on 2025-11-02 19:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('claim', '0038_claim_care_type_claim_code_pre_authorization_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='claim',
            name='rejection_pre_authorization_reason',
            field=models.TextField(blank=True, db_column='rejectionPreAuthorizationReason', null=True),
        ),
        migrations.AddField(
            model_name='claim',
            name='status_pre_authorization',
            field=models.SmallIntegerField(blank=True, db_column='ClaimPreAuthorizationStatus', null=True),
        ),
    ]
