# Generated by Django 4.2.11 on 2025-11-05 06:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('claim', '0039_claim_care_type_claim_refer_from_claim_refer_to_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='claim',
            name='audit_user_id_pre_auth',
            field=models.IntegerField(blank=True, db_column='AuditUserIDPreAuth', null=True),
        ),
        migrations.AddField(
            model_name='claim',
            name='date_pre_authorization_decision',
            field=models.IntegerField(blank=True, db_column='DatePreAuthorizationDecision', null=True),
        ),
        migrations.AddField(
            model_name='claim',
            name='date_pre_authorization_emergency',
            field=models.IntegerField(blank=True, db_column='DatePreAuthorizationEmergency', null=True),
        ),
    
    ]
