# Generated by Django 4.2.11 on 2025-11-07

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('claim', '0041_role_medical_officer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='claim',
            name='date_pre_authorization_emergency',
        ),
        migrations.RemoveField(
            model_name='claim',
            name='date_pre_authorization_decision',
        ),

        migrations.AddField(
            model_name='claim',
            name='date_pre_authorization_emergency',
            field=models.DateTimeField(
                blank=True,
                null=True,
                db_column='DatePreAuthorizationEmergency'
            ),
        ),
        migrations.AddField(
            model_name='claim',
            name='date_pre_authorization_decision',
            field=models.DateTimeField(
                blank=True,
                null=True,
                db_column='DatePreAuthorizationDecision'
            ),
        ),
    ]
